<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2014-08-08 22:57:12
 * @@Modify Date: 2018-03-14 22:54:24
 * @@Function:
 */
 ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $helpLabels = $this->helper('alothemes/labels');
    $helpTimer  = $this->helper('alothemes/timer'); $num = 1;
?>

<div class="mage-magictabs mc-<?php echo $this->escapeHtml($this->getType());?>">
    <?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <?php 
        $config = $this->getWidgetCfg(); 
        $width  = $config['widthImages'];
        $height = $config['heightImages'];
        $actions = isset($config['action']) ? $config['action'] : array();
    ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_rowCount = isset($config['row']) ? $config['row'] : 1; //$this->getColumnCount(); ?>
    <?php $j=0; $time = isset($config['productDelay']) ? $config['productDelay'] : 0; ?>
    <?php $tag = ($_rowCount >1) ? 'div' : 'ul'; ?>
    <<?php echo $tag ?> class="flexisel-content products-grid <?php echo $this->getType();?> zoomOut play">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($_rowCount > 1 && $i++%$_rowCount==0): ?>
            <ul class="products-grid-rows">
        <?php endif ?>
            <?php $t = $j*$time; $t .='ms'; $j++; ?>

                <li style="<?php echo "-webkit-animation-delay:$t;-moz-animation-delay:$t;-o-animation-delay:$t;animation-delay:$t" ?>;" class="item item-animate">
                    <div class="featured-product">
                        <div class="images-container product-img-content clearfix">
						    <div class="product-hover product-essential">
                                <?php 
                                    $product=Mage::getModel('catalog/product')->load($_product->getId());
                                    echo $this->getLayout()->createBlock('catalog/product_view_media')
                                    ->setProduct($product)
                                    ->setTemplate('catalog/product/view/media.phtml')->tohtml(); 
                                    // ->setTemplate('magiccart/magicproduct/product/view/media.phtml')->tohtml(); 
                                ?>
							</div>
                            <div class="products-textlink product-item-details clearfix">
								<h2 class="product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                                </h2>
								<?php if(in_array("review", $actions)):?>
                                   <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif ?>
                                
								<?php echo $this->getPriceHtml($_product, true) ?>
								<?php $product_label = $helpLabels->getLabels($_product); 
									if($product_label) :
								?>
								<div class="product-label clearfix">
									<?php echo $product_label; ?>
								</div>
							   <?php endif ?>
								<?php echo $helpTimer->getTimer($_product, $num); $num++;//Product Timer ?>
								<?php if($actions): ?>
									<div class="actions-cart">
										<?php if(in_array("cart", $actions)):?>
											<?php if($_product->isSaleable()): ?>
												<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart pull-left-none" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
											<?php else: ?>
												<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								<?php endif ?>
                            </div>
                        </div>
    				</div>
                </li>
            <?php if ($_rowCount > 1 && $i%$_rowCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
    </<?php echo $tag; ?>>
<?php endif; ?>
</div>


