<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2014-08-08 22:57:12
 * @@Modify Date: 2018-06-20 11:20:20
 * @@Function:
 */
 ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $helpLabels = $this->helper('alothemes/labels');
?>

<div class="mage-magictabs mc-<?php echo $this->escapeHtml($this->getType());?>">
    <?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <?php 
        $config = $this->getWidgetCfg(); 
        $width  = $config['widthImages'];
        $height = $config['heightImages'];
        $actions = isset($config['action']) ? $config['action'] : array();
    ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_rowCount = isset($config['row']) ? $config['row'] : 1; //$this->getColumnCount(); ?>
    <?php $j=0; $time = isset($config['productDelay']) ? $config['productDelay'] : 0; ?>
    <?php $tag = ($_rowCount >1) ? 'div' : 'ul'; ?>
    <<?php echo $tag ?> class="flexisel-content products-grid <?php echo $this->getType();?> zoomOut play">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($_rowCount > 1 && $i++%$_rowCount==0): ?>
            <ul class="products-grid-rows">
        <?php endif ?>
            <?php $t = $j*$time; $t .='ms'; $j++; ?>

                <li style="<?php echo "-webkit-animation-delay:$t;-moz-animation-delay:$t;-o-animation-delay:$t;animation-delay:$t" ?>;" class="item item-animate">
                    <div class="per-product clearfix">
						<div class="row-nor"><!-- them row -->
							<div class="images-container col-lg-6 col-md-6 col-sm-4 col-xs-4 img-product">
								<?php $product_label = $helpLabels->getLabels($_product); 
									if($product_label) :
									?>
									<div class="product-label clearfix">
										<?php echo $product_label; ?>
									</div>
								<?php endif ?>
								<div class="product-hover">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
										<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									 </a>
									 <div class="link-view <?php echo $_product->getTypeId(); ?>"> 
										<a title="<?php echo $this->__('Quick View') ?>" href="<?php echo $this->getUrl('magicshop/quickview/view', array('id' => $_product->getId(),'_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure())); ?>" class="link-quickview">
											<i class="fa fa-search-plus icons"></i><?php echo $this->__('Quick View')?>
										</a>
									</div>
								</div>
							</div>
							<div class="product details product-item-details products-textlink col-lg-6 col-md-6 col-sm-8 col-xs-8 product-featured-custom clearfix">
								<?php echo $this->getPriceHtml($_product, true) ?>
								<?php if($actions): ?>
									 <?php if(in_array("review", $actions)):?>
									   <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<?php endif ?>
								 <?php endif ?>
								<h2 class="product-name">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
								</h2>
								<?php if($actions): ?>
								<div class="hover-box actions clearfix">
									<div class="product-item-inner show-box clearfix">
									    <div class="product product-item-actions">
											<?php if(in_array("cart", $actions)):?>
											    <div class="actions-primary actions-cart alotheme-tooltip">
													<?php if($_product->isSaleable()): ?>
														<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span class="tooltip"><?php echo $this->__('Add to Cart') ?></span></span></button>
													<?php else: ?>
														<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
													<?php endif; ?>
												</div>
											<?php endif; ?>
											<ul class="add-to-links">
											    <?php if(in_array("wishlist", $actions)):?>
													<?php if ($this->helper('wishlist')->isAllow()) : ?>
														<li class="pull-left-none pull-wishlist alotheme-tooltip"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><i class="fa fa-heart icon icons"></i><span class="tooltip"><?php echo $this->__('Add to Wishlist') ?></span></a></li>
													<?php endif; ?>
												<?php endif; ?>
												<?php if(in_array("compare", $actions)):?>
													<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
														<li class="pull-left-none pull-compare alotheme-tooltip"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><i class="fa fa-retweet icon icons"></i><span class="tooltip"><?php echo $this->__('Compare') ?></span></a></li>
													<?php endif; ?>
												<?php endif; ?>
											</ul>
										</div>
									</div>
								</div>
								<?php endif ?>
							 </div>
						</div>
                    </div>
                </li>
            <?php if ($_rowCount > 1 && $i%$_rowCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
    </<?php echo $tag; ?>>
<?php endif; ?>
</div>
<?php if(Mage::getBlockSingleton('page/html_header')->getIsHomePage()) Mage::unregister('current_category'); ?>
